name: Run Composer Autoupdate

on:
  push:
    branches: [ dev, production ]

jobs:
  trigger_bedrock_updates:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Bedrock Updates
        uses: pressbooks/composer-autoupdate-bedrock@main
        with:
          triggered-by: ${{ github.repository }}
          token: ${{ secrets.PAT_COMPOSER_UPDATE }}
          branch: ${{ github.ref }}
