name: Run Composer Autoupdate

on:
  push:
    branches: [ dev, production ]

jobs:
  trigger_bedrock_updates:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Bedrock Updates
        uses: pressbooks/composer-autoupdate-bedrock@main
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SQS_ARN_DEV: ${{ secrets.AWS_SQS_ARN_DEV }}
          AWS_SQS_ARN_PROD: ${{ secrets.AWS_SQS_ARN_PROD }}
          INPUT_TRIGGERED_BY: ${{ github.repository }}
          INPUT_BRANCH: ${{ github.ref }}
