name: Lint Styles
on:
  push:
    branches: [ dev, production ]
  pull_request:
    branches:
      - dev
jobs:
  lint:
    uses: pressbooks/composer-autoupdate-bedrock/.github/workflows/lint-theme.yml@v1.1
